[uwsgi]
master = true
strict = true
need-app = true
lazy-apps = true
module = run_server
callable = app
enable-threads = true
thunder-lock = true
py-autoreload = 1
limit-post = 1073741824
auto-procname = true
